// Code generated by entc, DO NOT EDIT.

package material

const (
	// Label holds the string label denoting the material type in the database.
	Label = "material"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldDescribe holds the string denoting the describe field in the database.
	FieldDescribe = "describe"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldBuyDate holds the string denoting the buydate field in the database.
	FieldBuyDate = "buy_date"
	// Table holds the table name of the material in the database.
	Table = "materials"
)

// Columns holds all SQL columns for material fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCode,
	FieldDescribe,
	FieldPrice,
	FieldBuyDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
