// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CasbinRule is the predicate function for casbinrule builders.
type CasbinRule func(*sql.Selector)

// Material is the predicate function for material builders.
type Material func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Stock is the predicate function for stock builders.
type Stock func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
